-   id: yamale-schema-verify
    name: check yaml schema with Yamale
    description: prevents invalid yaml schemas from being committed
    entry: yamale
    language: python
    types: [yaml]
    pass_filenames: true
    stages: [pre-commit, pre-push, manual]
